### ISSUE TITLE
self_hosting.inference.LockedError

### ISSUE THREAD

**Issue by Sophisticated-IS** [smallcloudai/code-contrast#15] opened 2023-04-08 05:37 UTC
I'm running under Windows WSL2  with Rider plugin and docker container started OK, but I  didn't see any completion for C# code even with Enabled Force completion.  
**Model loaded:***
![image](https://user-images.githubusercontent.com/57034720/230705263-c60c28df-9aae-4146-a293-6040ec2931cd.png)
May it because of this error?:
![image](https://user-images.githubusercontent.com/57034720/230705271-4486d9c1-b86a-46da-8084-2b7711692a85.png)

**Comment by mitya52** [comment] 2023-04-14 19:11
@Sophisticated-IS please post here
- plugin version
- minimal example file to reproduce

**Comment by Sophisticated-IS** [comment] 2023-04-15 17:30
* Refact.ai 1.1.37
* Just any c# file from repo: https://github.com/Sophisticated-IS/SchoolSystem
In case I've worked for 1 hour and it didn't show once.

**Example file code:**

```
using AutoMapper;
using Backend.Application.ApiModels;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace Backend.Application.Queries.Handlers;

public sealed class GetFilteredPupilsHandler : IRequestHandler<GetFilteredPupilsQuery,IEnumerable<PupilWithId>>
{
    
    private readonly ISchoolDbContext _schoolDbContext;
    private readonly IMapper _mapper;
    public GetFilteredPupilsHandler(ISchoolDbContext schoolDbContext, IMapper mapper)
    {
        _schoolDbContext = schoolDbContext;
        _mapper = mapper;
    }
    
    public async Task<IEnumerable<PupilWithId>> Handle(GetFilteredPupilsQuery request, CancellationToken cancellationToken)
    {
        var pupils = await _schoolDbContext.Pupils
                                           .Where(p=>p.Name.Contains(request.Name) 
                                                     || p.SurName.Contains(request.SurName)
                                                     || p.MiddleName.Contains(request.MiddleName))
                                           .ToListAsync(cancellationToken: cancellationToken)
                                           .ConfigureAwait(false);
        
        return pupils.Select(p => _mapper.Map<PupilWithId>(p));
        
    }
}
```

**Comment by Sophisticated-IS** [comment] 2023-04-15 17:32
Also when i use force completion I see this in docker console:
![image](https://user-images.githubusercontent.com/57034720/232243994-68223c84-03ad-4e5f-87bc-61a4269a505c.png)

**Comment by mitya52** [comment] 2023-04-17 21:08
@Sophisticated-IS try to restart your server, problem should be gone

**Comment by Sophisticated-IS** [comment] 2023-04-28 04:25
@mitya52 yeah problem disappeared. But I am interested how long does it take to learn the model. Because my GPU is loaded 100% now but I get no hints/autocomplete offers.

**Comment by mitya52** [comment] 2023-05-05 21:15
@Sophisticated-IS I recommend you to disable experimental features (like multiple files completion). In some cases model doesn't make completion and it looks like it isn't working.
Another reason might be a slow GPU...but it must be very slow.
By the way, self hosted moved to another [repo](https://github.com/smallcloudai/refact-self-hosting). I'll close this issue, but lets [stay in touch](https://discord.com/invite/Jpa9DGeCfH).

**Closed by mitya52** 2023-05-05 21:15 UTC
